worker_processes auto;
events {
    worker_connections 1024;
}
http {
    server {
        listen 10000;
        location / {
            proxy_pass https://infinity-7zj.pages.dev;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host infinity-7zj.pages.dev;
            proxy_ssl_server_name on;
        }
    }
}
